const elementsMobile = [
  {
    id: "1",
    data: { label: "CSC 126" },
    targetPosition: "left",
    sourcePosition: "bottom",
    position: { x: window.innerWidth / 2 - 250, y: 20 },
  },
  {
    id: "2",
    data: { label: "200 level elective*" },
    position: { x: window.innerWidth / 2 - 400, y: 120 },
  },
  {
    id: "3",
    data: { label: "CSC 211" },
    position: { x: window.innerWidth / 2 - 100, y: 120 },
  },
  {
    id: "4",
    data: { label: "MTH 123 ~" },
    targetPosition: "right",
    sourcePosition: "bottom",
    position: { x: window.innerWidth / 4 - 300, y: 20 },
  },
  {
    id: "5",
    data: { label: "MTH 231 or MTH 230" },
    position: { x: window.innerWidth / 4 - 300, y: 120 },
  },
  {
    id: "5a",
    data: { label: "MTH 231 or MTH 230" },
    targetPosition: "left",
    position: { x: window.innerWidth / 4 - 300, y: 120 },
  },
  {
    id: "6",
    sourcePosition: "left",
    targetPosition: "right",
    data: { label: "MTH 229" },
    position: { x: window.innerWidth / 5 - 500, y: 120 },
  },
  {
    id: "7",
    data: { label: "MTH 232" },
    position: { x: window.innerWidth / 4 - 300, y: 220 },
  },
  {
    id: "8",
    data: { label: "CSC or MTH 228" },
    position: { x: window.innerWidth / 2 - 350, y: 220 },
  },
  {
    id: "9",
    data: { label: "CSC 326" },
    position: { x: window.innerWidth / 2, y: 220 },
  },
  {
    id: "10",
    data: { label: "CSC 220" },
    targetPosition: "left",
    position: { x: window.innerWidth / 2 + 150, y: 70 },
  },
  {
    id: "11",
    data: { label: "CSC 346 or ENS 220" },
    targetPosition: "top",
    position: { x: window.innerWidth / 2 + 450, y: 220 },
  },
  {
    id: "11a",
    data: { label: "CSC 346 or ENS 220" },
    sourcePosition: "right",
    position: { x: window.innerWidth / 2 + 450, y: 220 },
  },
  {
    id: "12",
    data: { label: "CSC 347" },
    targetPosition: "left",
    position: { x: window.innerWidth / 2 + 700, y: 220 },
  },
  {
    id: "13",
    data: { label: "MTH#" },
    targetPosition: "top",
    position: { x: window.innerWidth / 4 - 500, y: 320 },
  },
  {
    id: "14",
    data: { label: "MTH#" },
    targetPosition: "top",
    position: { x: window.innerWidth / 4 - 250, y: 320 },
  },
  {
    id: "15",
    data: { label: "CSC 382" },
    targetPosition: "top",
    position: { x: window.innerWidth / 4 + 50, y: 320 },
  },
  {
    id: "16",
    data: { label: "CSC 330" },
    targetPosition: "top",
    position: { x: window.innerWidth / 2 - 50, y: 350 },
  },
  {
    id: "17",
    data: { label: "CSC 315" },
    targetPosition: "top",
    position: { x: window.innerWidth / 2 + 300, y: 320 },
  },
  {
    id: "18",
    data: { label: "CSC 446" },
    targetPosition: "top",
    position: { x: window.innerWidth / 2 + 600, y: 320 },
  },
  {
    id: "19",
    data: { label: "CSC 332" },
    targetPosition: "top",
    position: { x: window.innerWidth / 2 + 150, y: 420 },
  },
  {
    id: "19a",
    data: { label: "CSC 332" },
    sourcePosition: "right",
    position: { x: window.innerWidth / 2 + 150, y: 420 },
  },
  {
    id: "20",
    data: { label: "CSC 305" },
    targetPosition: "left",
    position: { x: window.innerWidth / 2 + 400, y: 420 },
  },
  {
    id: "21",
    data: { label: "400 level elective*" },
    position: { x: window.innerWidth / 3 - 50, y: 420 },
  },
  {
    id: "22",
    data: { label: "CSC 490**" },
    position: { x: window.innerWidth / 3 + 50, y: 540 },
  },
  {
    id: "23",
    data: { label: "CSC 430" },
    position: { x: window.innerWidth / 3 + 350, y: 540 },
  },
  {
    id: "e1-2",
    source: "1",
    target: "2",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e1-3",
    source: "1",
    target: "3",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e4-5",
    source: "4",
    target: "5",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e1-4",
    source: "1",
    target: "4",
    arrowHeadType: "arrowclosed",
    type: "smoothstep",
  },
  {
    id: "e4-1",
    source: "4",
    target: "1",
    arrowHeadType: "arrowclosed",
    type: "smoothstep",
  },
  {
    id: "e5-6",
    source: "5",
    target: "6",
    arrowHeadType: "arrowclosed",
    type: "smoothstep",
  },
  {
    id: "e6-5a",
    source: "6",
    target: "5a",
    arrowHeadType: "arrowclosed",
    type: "smoothstep",
  },
  {
    id: "e6-7",
    source: "6",
    target: "7",
    arrowHeadType: "arrowclosed",
    type: "smoothstep",
  },
  {
    id: "e3-8",
    source: "3",
    target: "8",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e3-9",
    source: "3",
    target: "9",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e1-10",
    source: "1",
    target: "10",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e10-11",
    source: "10",
    target: "11",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e11a-12",
    source: "11a",
    target: "12",
    arrowHeadType: "arrowclosed",
    type: "smoothstep",
  },
  {
    id: "e12-11a",
    source: "12",
    target: "11a",
    arrowHeadType: "arrowclosed",
    type: "smoothstep",
  },
  {
    id: "e7-13",
    source: "7",
    target: "13",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e7-14",
    source: "7",
    target: "14",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e7-15",
    source: "7",
    target: "15",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e8-15",
    source: "8",
    target: "15",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e9-15",
    source: "9",
    target: "15",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e9-16",
    source: "9",
    target: "16",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e9-17",
    source: "9",
    target: "17",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e11-18",
    source: "11",
    target: "18",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e9-19",
    source: "9",
    target: "19",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e10-19",
    source: "10",
    target: "19",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e19a-20",
    source: "19a",
    target: "20",
    arrowHeadType: "arrowclosed",
    type: "smoothstep",
  },
  {
    id: "e20-19a",
    source: "20",
    target: "19a",
    arrowHeadType: "arrowclosed",
    type: "smoothstep",
  },
  {
    id: "e9-21",
    source: "9",
    target: "21",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e16-22",
    source: "16",
    target: "22",
    arrowHeadType: "arrowclosed",
  },
  {
    id: "e16-23",
    source: "16",
    target: "23",
    arrowHeadType: "arrowclosed",
  },
];

export default elementsMobile;
